#!/bin/bash

if which mvn >/dev/null 2>/dev/null && find -maxdepth 1 -type f -name pom.xml 
then
	mvn clean install
	if [ $? -ne 0 ]; then
		echo -e "\e[00;31m[GIT-HOOKS] Error while testing!\e[00m"
		exit 1
	else
		exit 0
	fi  
fi
