theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "xrandr"
#icons = true
#resolution = true
interval = 2
 
[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "github"
format = "C:{comment}.M:{mention}.R:{review_requested}"

[[block]]
block = "net"
device = "wlp59s0"
interval = 5

[[block]]
block = "music"
max_width = 21
marquee = false
player = "spotify"
buttons = ["play", "next"]
 
[[block]]
block = "bluetooth"
mac = "90:78:41:23:0D:15"

[[block]]
block = "bluetooth"
mac = "DC:2C:26:E8:79:03"

[[block]]
block = "sound"
show_volume_when_muted = true
 
[[block]]
block = "cpu"
interval = 0.7
 
[[block]]
block = "memory"
interval = 5
info_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
 
[[block]]
block = "battery"
format = "{time} {bar}"
 
#[[block]]
#block = "custom"
#command = "curl 'wttr.in/'$(curl https://ipinfo.io/ | jq -r .city)'?format=%c%t' || echo Not avaiable"
#interval = 6000

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

